firstName = str(input("What is your first name ? "))
lastName = input("What is your last name ? ")
location = input("What is your location ? ")
age = input("What is your age ? ")
print("Hello " + firstName + " " + lastName + "! you location is " + location + " and you are " + age + " years old")